author: Cnangel
name: Build RPM packages
description: Build RPM packages with rpmbuild in a flexible environment.
inputs:
  spec_file:
    description: Path to the spec file
    required: true
    default: '*.spec'
  additional_repos:
    description: A list of additional repositories to enable
    required: false
  is_output_srpm:
    description: Whether output srpm package
    default: true
    required: false
  dnf_opts:
    description: Options to be passed to dnf or yum
    required: false
  artifacts_dir:
    default: 'rpmbuild'
    description: Directory path relative to $GITHUB_WORKSPACE to place the built packages in
    required: true
  before_build_hook:
    description: Shell command(s) to execute after installing build dependencies
      and before executing rpmbuild
    required: false
  rpmbuild_opts:
    description: Options to be passed to rpmbuild
    default: '-bb'
    required: false
  docker_image:
    default: 'cnangel/fedora38'
    description: Name of a Docker image to build inside or path of a Dockerfile
    required: true
  extra_build_deps:
    description: Extra packages to be installed as build dependencies
    required: false
  extra_docker_args:
    description: Additional arguments to 'docker run' when starting the build container
    required: false
  host_arch:
    description: Foreign architecture to setup cross-compilation for
    required: false
  source_dir:
    default: './'
    description: Path relative to $GITHUB_WORKSPACE that contains the package sources
    required: true

outputs:
  rpm_dir_names:
    description: Path to RPM files
    value: ${{ steps.rpm-build.outputs.rpm_dir_names }}
  rpm_dir_path:
    description: Path to RPM directory
    value: ${{ steps.rpm-build.outputs.rpm_dir_path }}
  srpm_dir_names:
    description: Path to Source RPM files
    value: ${{ steps.rpm-build.outputs.srpm_dir_names }}
  srpm_dir_path:
    description: Path to Source directory
    value: ${{ steps.rpm-build.outputs.srpm_dir_path }}

runs:
  using: composite
  steps:
    - id: rpm-build
      env:
        INPUT_SPEC_FILE: ${{ inputs.spec_file }}
        INPUT_ADDITIONAL_REPOS: ${{ inputs.additional_repos }}
        INPUT_IS_OUTPUT_SRPM: ${{ inputs.is_output_srpm }}
        INPUT_DNF_OPTS: ${{ inputs.dnf_opts }}
        INPUT_ARTIFACTS_DIR: ${{ inputs.artifacts_dir }}
        INPUT_BEFORE_BUILD_HOOK: ${{ inputs.before_build_hook }}
        INPUT_RPMBUILD_OPTS: ${{ inputs.rpmbuild_opts }}
        INPUT_DOCKER_IMAGE: ${{ inputs.docker_image }}
        INPUT_EXTRA_BUILD_DEPS: ${{ inputs.extra_build_deps }}
        INPUT_EXTRA_DOCKER_ARGS: ${{ inputs.extra_docker_args }}
        INPUT_HOST_ARCH: ${{ inputs.host_arch }}
        INPUT_SOURCE_DIR: ${{ inputs.source_dir }}
      run: ${{ github.action_path }}/scripts/run
      shell: bash

branding:
  color: red
  icon: package
