#!/bin/sh

set -eu

export RPM_BUILD_OPTIONS="${RPM_BUILD_OPTIONS:+$RPM_BUILD_OPTIONS}"
export INPUT_HOST_ARCH="${INPUT_HOST_ARCH:+--target $INPUT_HOST_ARCH}"
if [[ "$INPUT_RPMBUILD_OPTS" =~ t ]]
then
	name=$(grep -i 'Name:' "$INPUT_SPEC_FILE" |awk '{print $2}')
	version=$(grep -i 'Version:' "$INPUT_SPEC_FILE" |awk '{print $2}')
	rpmbuild $INPUT_RPMBUILD_OPTS "/github/home/rpmbuild/SOURCES/${name}-${version}.tar.gz" $RPM_BUILD_OPTIONS $INPUT_HOST_ARCH
else
	rpmbuild $INPUT_RPMBUILD_OPTS "/github/workspace/$INPUT_SPEC_FILE" $RPM_BUILD_OPTIONS $INPUT_HOST_ARCH
fi
