#!/bin/bash

set -x

echo "rpm_dir_names=$(find "$INPUT_ARTIFACTS_DIR/RPMS" -name "*.rpm" | jo -a | jq -r 'join(",")')"
if [ "$INPUT_IS_OUTPUT_SRPM" == "true" ]
then
	echo "srpm_dir_names=$(find "$INPUT_ARTIFACTS_DIR/SRPMS" -name "*.rpm" | jo -a | jq -r 'join(",")')"
fi

