#!/bin/bash

set -x

dnf_cmd=$(which yum 2>/dev/null)
if [ -x "$(which dnf 2>/dev/null)" ]
then
	dnf_cmd=$(which dnf)
else
	if [ ! -x "$dnf_cmd" ]
	then
		echo "No yum or dnf command"
		exit 1
	fi
fi

if ! rpmdev-setuptree;
then
	echo "rpmdev-setuptree fail"
	exit 1
fi

for repo_file in $(echo "$INPUT_ADDITIONAL_REPOS" | jq -r 'join("\n")')
do
	"$dnf_cmd" install -y "$repo_file"
done

yum-builddep -y "${INPUT_SOURCE_DIR}/${INPUT_SPEC_FILE}"

if [ -n "$INPUT_EXTRA_BUILD_DEPS" ]
then
	# shellcheck disable=SC2086
	$dnf_cmd install -y $INPUT_DNF_OPTS -- $INPUT_EXTRA_BUILD_DEPS
fi

