#!/bin/sh

set -eu

dnf_cmd=$(which yum 2>/dev/null)
if [ -x "$(which dnf 2>/dev/null)" ]
then
	dnf_cmd=$(which dnf)
else
	if [ ! -x "$dnf_cmd" ]
	then
		echo "No yum or dnf command"
		exit 1
	fi
fi

rpmdev-setuptree
name=$(grep -i 'Name:' "$INPUT_SPEC_FILE" |awk '{print $2}')
version=$(grep -i 'Version:' "$INPUT_SPEC_FILE" |awk '{print $2}')
spec_file=$(basename "$INPUT_SPEC_FILE")
cp "/github/workspace/${INPUT_SPEC_FILE}" "/github/home/rpmbuild/SPECS/${spec_file}"
git archive HEAD --format tar.gz --prefix "${name}-${version}/" -o "/github/home/rpmbuild/SOURCES/${name}-${version}.tar.gz"
for repo_file in $(echo "$INPUT_ADDITIONAL_REPOS" | jq -r 'join("\n")')
do
	"$dnf_cmd" install -y "$repo_file"
done

yum-builddep -y "/github/home/rpmbuild/SPECS/${spec_file}"

if [ -n "$INPUT_EXTRA_BUILD_DEPS" ]
then
	"$dnf_cmd" install -y "$INPUT_DNF_OPTS" -- "$INPUT_EXTRA_BUILD_DEPS"
fi
