#!/bin/bash

set -x

mkdir -p "$INPUT_ARTIFACTS_DIR/"
cp -rf "/root/rpmbuild/RPMS" "$INPUT_ARTIFACTS_DIR/"
if [ "$INPUT_IS_OUTPUT_SRPM" == "true" ]
then
	cp -rf "/root/rpmbuild/SRPMS" "$INPUT_ARTIFACTS_DIR/"
fi
